## NumPy

NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

In [1]:
import numpy as np

In [2]:
# declare a vector using a list as the argument
v = np.array([1,2,3,4])
v

array([1, 2, 3, 4])

In [3]:
# NumPy’s array class is called ndarray. 
a = np.arange(10).reshape(2, 5)
a


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [4]:
a.size

10

In [5]:
type(a)

numpy.ndarray

In [6]:
a.shape

(2, 5)

In [7]:
# declare a matrix using a nested list as the argument
M = np.array([[1,2],[3,4]])
M

array([[1, 2],
       [3, 4]])

Here is a way to create an array with a range of numbers

In [8]:
# arguments: start, stop, step
x = np.arange(0, 10, 1)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
x, y = np.mgrid[0:5, 0:5]
x

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [10]:
y

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

### Indexing, Slicing and Iterating

One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.

In [11]:
a = np.arange(10)**3
a    

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [12]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

Multidimensional arrays can have one index per axis. These indices are given in a tuple separated by commas:

In [13]:
def f(x,y):
    return 10*x+y

b = np.fromfunction(f,(4,4),dtype=int)
b


array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33]])

In [14]:
b[1:3, : ]      # # each column in the second and third row of b

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [15]:
b[-1]     # last row

array([30, 31, 32, 33])

In [16]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]


### Changing the shape of an array

In [17]:
a = np.floor(10*np.random.random((3,4)))
a

array([[ 1.,  6.,  2.,  7.],
       [ 2.,  0.,  1.,  2.],
       [ 8.,  6.,  5.,  3.]])

In [18]:
a.ravel() 

array([ 1.,  6.,  2.,  7.,  2.,  0.,  1.,  2.,  8.,  6.,  5.,  3.])

In [19]:
a.reshape(6,2) # 6 rows and 2 columns

array([[ 1.,  6.],
       [ 2.,  7.],
       [ 2.,  0.],
       [ 1.,  2.],
       [ 8.,  6.],
       [ 5.,  3.]])

### Stacking Arrays (Horizonal or Vertical)

In [20]:
a = np.floor(10*np.random.random((2,2)))
a

array([[ 3.,  2.],
       [ 1.,  1.]])

In [21]:
b = np.floor(10*np.random.random((2,2)))
b

array([[ 4.,  7.],
       [ 8.,  4.]])

In [22]:
np.vstack((a,b))

array([[ 3.,  2.],
       [ 1.,  1.],
       [ 4.,  7.],
       [ 8.,  4.]])

In [23]:
 np.hstack((a,b))

array([[ 3.,  2.,  4.,  7.],
       [ 1.,  1.,  8.,  4.]])